version: 0.2.2-dev-{build}

image: Ubuntu1804

install:
- sh: sudo apt-get update
- sh: sudo apt-get install -y libpurple-dev libglib2.0-dev libxml2-dev libcmocka-dev mingw-w64 unzip

build: off

test_script:
- sh: CMOCKA_MESSAGE_OUTPUT=XML CMOCKA_XML_FILE=build/cmocka_results.xml make test

after_test:
- sh: curl -v -F "file=@$APPVEYOR_BUILD_FOLDER/build/cmocka_results.xml" "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
- sh: bash <(curl -s https://codecov.io/bash) -g test/ -B $APPVEYOR_REPO_BRANCH -b $APPVEYOR_BUILD_VERSION

artifacts:
  - path: $(APPVEYOR_BUILD_FOLDER)/build/carbons.so
    name: carbons-$(APPVEYOR_BUILD_NUMBER)-$(APPVEYOR_REPO_COMMIT).so