version: 0.2.2-dev-{build}

image: Ubuntu1804

install:
- sh: sudo apt-get update
- sh: sudo apt-get install -y libpurple-dev libglib2.0-dev libxml2-dev libcmocka-dev

build: off

test_script:
- sh: make test

after_test:
- sh: bash <(curl -s https://codecov.io/bash) -g test/ -B $APPVEYOR_REPO_BRANCH -b $APPVEYOR_BUILD_NUMBER